name: Build Firmware
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Flipper SDK
      run: |
        git clone https://github.com/flipper-io/flipper.git
        cd flipper
        make deps
    
    - name: Build firmware
      run: |
        cd app
        make clean
        make
